# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger: none

pool:
  vmImage: ubuntu-latest

steps:
  - bash: |
      pwd
      ls -ltr
  # - task: Kubernetes@1
  #   displayName: kubectl apply using arguments
  #   inputs:
  #     connectionType: Azure Resource Manager
  #     azureSubscriptionEndpoint: service-connection-k8s
  #     azureResourceGroup: backstage-deployment
  #     kubernetesCluster: backstage-k8s
  #     command: apply
  #     arguments: -f kubernetes/namespace.yaml
  - task: Kubernetes@1
    displayName: kubectl apply using arguments
    inputs:
      connectionType: Azure Resource Manager
      azureSubscriptionEndpoint: service-connection-k8s
      azureResourceGroup: backstage-deployment
      kubernetesCluster: backstage-k8s
      command: apply
      arguments: -f kubernetes/backstage.yaml -f kubernetes/backstage-service.yaml