trigger: none

pool:
  vmImage: ubuntu-latest

steps:
  - task: Kubernetes@1
    displayName: kubectl apply using arguments
    inputs:
      connectionType: Azure Resource Manager
      azureSubscriptionEndpoint: service-connection-k8s
      azureResourceGroup: MyResourceGroup
      kubernetesCluster: aks64d8
      command: apply
      arguments: -f ../kubernetes/namespace.yaml

  - task: Kubernetes@1
    displayName: kubectl apply using arguments
    inputs:
      connectionType: Azure Resource Manager
      azureSubscriptionEndpoint: service-connection-k8s
      azureResourceGroup: MyResourceGroup
      kubernetesCluster: aks64d8
      command: apply
      arguments: -f ../kubernetes/backstage.yaml -f ../kubernetes/backstage-service.yaml
